spring.application.name=Mapping
# Datos de conexion
spring.datasource.url=jdbc:postgresql://34.172.134.123:5432/energiainteligente
spring.datasource.username=postgres
spring.datasource.password=isei2025*
server.port=8081

# Configuración JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Habilitar soporte de UUID
spring.datasource.hikari.connection-init-sql=CREATE EXTENSION IF NOT EXISTS "pgcrypto";

